### ISSUE TITLE
Why controllers are classes and why there is no async/await mechanism

### ISSUE THREAD

**Issue by kaskar2008** [ivyjs/framework#1]
Why controllers are classes? If I set route handler to a controller, like as `Route.get('/', 'HomeController@home');` method `home` will be called with `apply` construction and no context will be given. It makes no sense.

Why there is no async/await mechanism? What if I need to get some data from database asynchronously. How can I achieve that in the controller?

Thank you.

**Comment by alexa026** [comment]
Both of your questions are completely logical and the answer of them are just the same. This is not yet the stable version, its < 1.0, and its not ready for some huge things. Im currently out of time for some further development, but this will keep going in the future.

**Comment by kaskar2008** [comment]
@alexa026, I remembered this issue and finally got a free time so resolve it :)

#2 solves this problem
